---
- name: "Fetch ServiceNow API Access Token"
  hosts: localhost
  gather_facts: true
  become: false
  tasks:
    - name: "Fetch Access token"
#  no_log: true
      ansible.builtin.uri:
        method: POST
        url: "{{token_endpoint}}"
        body_format: form-urlencoded
        body:
          grant_type   : "{{grant_type}}"
          scope        : "{{vault_scope}}"
          client_id    : "{{vault_client_id}}"
          client_secret: "{{vault_client_secret}}"
        status_code: [200]
        return_content: true
      register: response_body

    - name: "Add fetched time to token data"
      ansible.builtin.set_fact:
        token_data: "{{ response_body.json | default([]) | combine({'fetched_time' : ansible_date_time.epoch })}}"
      when: response_body.status == 200


    - name: "Store Token data in a file" 
      ansible.builtin.copy:
        content: "{{token_data | to_nice_json}}"
        dest: "vault_access_token"
        force: true
      when: response_body.status == 200
    
    - name: "Convert Token to Vault variable"
#   no_log: true
      ansible.builtin.shell: 
        cmd: "ansible-vault encrypt vault_access_token --vault-id  \"$HOME/ansible-practice/passfile\""
      when: response_body.status == 200
      register: vault_token

