---
- name: "Fetch ServiceNow API Access Token"
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: "Fetch Access token"
      no_log: true
      ansible.builtin.uri:
        method: POST
        url: "{{token_endpoint}}"
        body_format: form-urlencoded
        body:
          grant_type   : "{{grant_type}}"
          scope        : "{{vault_scope}}"
          client_id    : "{{vault_client_id}}"
          client_secret: "{{vault_client_secret}}"
        status_code: [200]
        return_content: true
      register: response_body

    - name: "Convert to Vault string"
      no_log: true
      ansible.builtin.shell: 
        cmd: "ansible-vault encrypt_string \"{{response_body.json.access_token}}\" --vault-id  \"$HOME/ansible-practice/passfile\" --name 'vault_access_token'"
      when: response_body.status == 200
      register: vault_token

    - name: "Store token" 
      ansible.builtin.copy:
        content: "{{vault_token.stdout}}"
        dest: "$HOME/ansible-practice/host_vars/{{inventory_hostname}}/vault_access_token"
        force: true
