---
- name: "Fetch ServiceNow API Access Token"
  hosts: dc3auooapppd01b.na.msmps.net
  gather_facts: false
  become: false
  tasks:
    - name: "Fetch Access token"
      ansible.builtin.uri:
        method: POST
        url: "{{token_endpoint}}"
        body_format: form-urlencoded
        body:
          grant_type   : "{{grant_type}}"
          scope        : "{{vault_scope}}"
          client_id    : "{{vault_client_id}}"
          client_secret: "{{vault_client_secret}}"
        status_code: [200]
        return_content: true
      register: response_body

    - name: "Print Token"
      ansible.builtin.debug:
       msg: "{{response_body.json.access_token}}"
      when: response_body.status == 200
      
    


